In [2]:
import pandas as pd
import os

In [3]:
data=pd.read_csv("loan.csv")

In [4]:
data.head()

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score  Loan offer
0           5    0.0         1.0        0.0  50.0       34.940           0
1           3    1.0         0.0        0.0  18.0        0.891           1
2          66    0.0         1.0        0.0   5.0        0.330           1
3          70    0.0         1.0        1.0  31.0        0.037           0
4          96    0.0         1.0        0.0  30.0        0.038           1

2. Check Last 5 Rows of The Dataset

In [5]:
data.tail()

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score  Loan offer
1335       34100    0.0         1.0        0.0   NaN        0.576           1
1336       34110    1.0         1.0        0.0  46.0        3.705           0
1337       34113    1.0         1.0        0.0  39.0        0.099           1
1338       34145    1.0         0.0        0.0   8.0        3.177           0
1339       34153    1.0         1.0        0.0  30.0        0.688           1

3. Find Shape of Our Dataset (Number of Rows And Number of Columns)

In [7]:
data.shape

(1340, 7)

In [8]:
print("Number of Rows: ",data.shape[0])
print("Number of Columns: ",data.shape[1])

Number of Rows:  1340
Number of Columns:  7


4. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Cutomer id   1340 non-null   int64  
 1   Cards        1328 non-null   float64
 2   Debit card   1299 non-null   float64
 3   Insurance    1292 non-null   float64
 4   Age          1151 non-null   float64
 5   Cibil Score  1340 non-null   float64
 6   Loan offer   1340 non-null   int64  
dtypes: float64(5), int64(2)
memory usage: 73.4 KB


5. Check Null Values In The Dataset

In [10]:
data.isnull().sum()

Cutomer id       0
Cards           12
Debit card      41
Insurance       48
Age            189
Cibil Score      0
Loan offer       0
dtype: int64

In [11]:
# Missing Percentage

data.isnull().sum()*100 / len(data)

Cutomer id      0.000000
Cards           0.895522
Debit card      3.059701
Insurance       3.582090
Age            14.104478
Cibil Score     0.000000
Loan offer      0.000000
dtype: float64

In [14]:
data.head(1)

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score  Loan offer
0           5    0.0         1.0        0.0  50.0        34.94           0

In [15]:
# making a list of columns with missing percentage < 5%

columns = ['Debit card','Insurance']

In [16]:
# dropping rows and columns with missing percentage less than 5%

data = data.dropna(subset=columns) # as default axis=0 (meaning drop rows which contain missing values)

In [17]:
# checking missing percentage again

data.isnull().sum()*100 / len(data)

Cutomer id      0.000000
Cards           0.704225
Debit card      0.000000
Insurance       0.000000
Age            13.693271
Cibil Score     0.000000
Loan offer      0.000000
dtype: float64

All columns, except 'Cards' and 'Age' are handled and these column's missing percentage is more than 5%, so we can't delete row them, we've to fill the missing values with appropriate values.

In [18]:
data['Age'].unique()

array([50., 18.,  5., 31., 30., 35.,  9., 34., 60., nan, 37., 41.,  7.,
       40., 58.,  3., 38., 39., 54., 61.,  0., 16., 17., 33., 46., 55.,
        1., 19., 10., 44.,  4., 56., 63., 47., 57., 11.,  8., 71.,  6.,
       43., 69., 48., 75., 80., 66., 13., 51., 15., 65., 14., 49., 77.,
       36., 45., 53., 59., 67., 83., 64., 70., 73., 95., 88., 78., 84.,
       68., 74., 86., 76.])

In [19]:
data['Age'].mode()[0]

10.0

In [20]:
data['Age'] = data['Age'].fillna(data['Age'].mode()[0])

C:\Users\San Ram\AppData\Local\Temp\ipykernel_21752\1926125166.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Age'] = data['Age'].fillna(data['Age'].mode()[0])


In [22]:
data['Cards'].unique()


array([ 0.,  1., nan])

In [23]:
data['Cards'].mode()[0]


1.0

In [24]:
data['Cards'] = data['Cards'].fillna(data['Cards'].mode()[0])

C:\Users\San Ram\AppData\Local\Temp\ipykernel_21752\1359011191.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Cards'] = data['Cards'].fillna(data['Cards'].mode()[0])


In [25]:
data.isnull().sum()*100 / len(data)

Cutomer id     0.0
Cards          0.0
Debit card     0.0
Insurance      0.0
Age            0.0
Cibil Score    0.0
Loan offer     0.0
dtype: float64

All missing values are handled.

7. Handling Categorical Columns

In [26]:
data.sample(5)

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score  Loan offer
1012       15901    1.0         1.0        0.0  78.0        0.015           1
571         4806    1.0         1.0        0.0  44.0        3.313           1
795        10677    0.0         0.0        0.0  49.0        3.763           1
1017       16013    0.0         1.0        0.0   9.0        1.908           0
912        13500    0.0         1.0        0.0  34.0        4.500           0

In [27]:
# replace 3+ with 3

data['Debit card'] = data['Debit card'].replace(to_replace="3+",value='3')

C:\Users\San Ram\AppData\Local\Temp\ipykernel_21752\412791581.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Debit card'] = data['Debit card'].replace(to_replace="3+",value='3')


In [28]:
data['Debit card'].unique()

array([1., 0.])

In [30]:
data['Loan offer'].unique()

array([0, 1], dtype=int64)

8.Store Feature Matrix In X And Response (Target) In Vector y

In [31]:
X = data.drop('Loan offer', axis=1)

In [32]:
y = data['Loan offer']

9. Feature Scaling

In [33]:
X.head()

Cutomer id  Cards  Debit card  Insurance   Age  Cibil Score
0           5    0.0         1.0        0.0  50.0       34.940
1           3    1.0         0.0        0.0  18.0        0.891
2          66    0.0         1.0        0.0   5.0        0.330
3          70    0.0         1.0        1.0  31.0        0.037
4          96    0.0         1.0        0.0  30.0        0.038

Customer id,Cards, Debit card, Insurance, Age , Cibil Score values are in the same range.
Loan offer is the target variable

10. Splitting The Dataset Into The Training Set And Test Set & Applying K-Fold Cross Validation

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
import numpy as np

In [35]:
model_df = {}

def model_val(model,X,y):
    # spliting dataset for training and testing
    X_train,X_test,y_train,y_test = train_test_split(X,y,
                                                   test_size=0.20,
                                                   random_state=42)
    
    # training the model
    model.fit(X_train, y_train)
    
    # asking model for prediction
    y_pred = model.predict(X_test)
    
    # checking model's prediction accuracy
    print(f"{model} accuracy is {accuracy_score(y_test,y_pred)}")
    
    # to find the best model we use cross-validation, thru this we can compare different algorithms
    # In this we use whole dataset to for testing not just 20%, but one at a time and summarize 
    # the result at the end.
    
    # 5-fold cross-validation (but 10-fold cross-validation is common in practise)
    score = cross_val_score(model,X,y,cv=5)  # it will divides the dataset into 5 parts and during each iteration 
                                             # uses (4,1) combination for training and testing 
    
    print(f"{model} Avg cross val score is {np.mean(score)}")
    model_df[model] = round(np.mean(score)*100,2)
    

11. Logistic Regression

In [36]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

# passing this model object of LogisticRegression Class in the function we've created
model_val(model,X,y)

LogisticRegression() accuracy is 0.734375
LogisticRegression() Avg cross val score is 0.6681832107843138


In [37]:
model_df

{LogisticRegression(): 66.82}

12. SVC (Support Vector Classifier)

In [38]:
from sklearn import svm

model = svm.SVC()
model_val(model,X,y)

SVC() accuracy is 0.453125
SVC() Avg cross val score is 0.5070373774509804


In [39]:
model_df

{LogisticRegression(): 66.82, SVC(): 50.7}

13. Decision Tree Classifier

In [40]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model_val(model,X,y)

DecisionTreeClassifier() accuracy is 0.609375
DecisionTreeClassifier() Avg cross val score is 0.5884221813725491


In [41]:
model_df

{LogisticRegression(): 66.82, SVC(): 50.7, DecisionTreeClassifier(): 58.84}

14. Random Forest Classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier

model =RandomForestClassifier()
model_val(model,X,y)

RandomForestClassifier() accuracy is 0.69921875
RandomForestClassifier() Avg cross val score is 0.6792156862745099


In [43]:
model_df

{LogisticRegression(): 66.82,
 SVC(): 50.7,
 DecisionTreeClassifier(): 58.84,
 RandomForestClassifier(): 67.92}

Clearly, LogisticRegression near to RandomForest is the best model with accuracy 66.82 compared with other two(SVC & DecisonTree)

Logistic Regression

In [44]:
# Let's tune hyper parameters of LogisticRegression (we've choosen 'C' and 'solver' parameter for tuning)

log_reg_grid = {"C": np.logspace(-4,4,20),
                "solver": ['liblinear']}

In [48]:
# In RandomizedSearchCV we've to pass estimator, which is nothing but Algo class, It will return
# a model with it's Hyper Parameter already set and we've to train that model, with our dataset

rs_log_reg = RandomizedSearchCV(LogisticRegression(),
                   param_distributions = log_reg_grid,
                   n_iter=20, cv=5, verbose=True)

In [49]:
# Let's train our model with these set hyper parameters for optimized results.
from sklearn.model_selection import RandomizedSearchCV
rs_log_reg.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': array([1.00000000e-04, 2.63665090e-04, 6.95192796e-04, 1.83298071e-03,
       4.83293024e-03, 1.27427499e-02, 3.35981829e-02, 8.85866790e-02,
       2.33572147e-01, 6.15848211e-01, 1.62377674e+00, 4.28133240e+00,
       1.12883789e+01, 2.97635144e+01, 7.84759970e+01, 2.06913808e+02,
       5.45559478e+02, 1.43844989e+03, 3.79269019e+03, 1.00000000e+04]),
                                        'solver': ['liblinear']},
                   verbose=True)

In [50]:
rs_log_reg.best_score_

0.7010937500000001

In [51]:
rs_log_reg.best_params_

{'solver': 'liblinear', 'C': 0.03359818286283781}

Random Forest Classifier

In [52]:
rf_grid = {'n_estimators':np.arange(10,1000,10),
           'max_features':['log2','sqrt'],
           'max_depth':[None,3,5,10,20,30],
           'min_samples_split':[2,5,20,50,100],
           'min_samples_leaf':[1,2,5,10]
          }

In [53]:
rs_rf = RandomizedSearchCV(RandomForestClassifier(),
                  param_distributions = rf_grid,
                  cv=5,
                  n_iter=20,
                  verbose=True)

In [54]:
rs_rf.fit(X,y)

Fitting 5 folds for each of 20 candidates, totalling 100 fits


RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=20,
                   param_distributions={'max_depth': [None, 3, 5, 10, 20, 30],
                                        'max_features': ['log2', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 20, 50,
                                                              100],
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260,
       270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390,
       400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520,
       530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650,
       660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780,
       790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910,
       920, 930, 940, 950, 960, 970, 980, 990])},
                   verbose=True)

In [55]:
rs_rf.best_score_


0.7261488970588236

In [56]:
rs_rf.best_params_


{'n_estimators': 460,
 'min_samples_split': 5,
 'min_samples_leaf': 2,
 'max_features': 'sqrt',
 'max_depth': 3}

In [ ]:
LogisticRegression score Before Hyperparameter Tuning: 66.82
LogisticRegression score after Hyperparameter Tuning: 70.10 

-------------------------------------------------------------------------------

RandomForestClassifier score Before Hyperparameter Tuning: 67.92
RandomForestClassifier score after Hyperparameter Tuning: 72.61

Selecting Random Forest Classifier for Production with 72.61 accuracy. Earlier it was Logistic Regression with 70.10.

17. Save The Model
Before we save our best model RandomForestClassifier for Production, we've to train our Model on the entire dataset with best parameters that we've just found.

In [57]:
X = data.drop('Loan offer',axis=1)
y = data['Loan offer']

In [58]:
rf = RandomForestClassifier(n_estimators = 270,
                            min_samples_split = 5,
                            min_samples_leaf = 5,
                            max_features = 'sqrt',
                            max_depth = 5)

In [59]:
rf.fit(X,y)

RandomForestClassifier(max_depth=5, min_samples_leaf=5, min_samples_split=5,
                       n_estimators=270)